package pl.nowator_zpu.warehouse_app.entities;
// Generated 20 sie 2019, 07:51:47 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Shelfs generated by hbm2java
 */
@Entity
@Table(name = "shelfs", catalog = "db_warehouse", uniqueConstraints = @UniqueConstraint(columnNames = "shelf"))
public class Shelfs implements java.io.Serializable {

	private Integer shelfId;
	private String shelf;
	private Set<Parts> parts = new HashSet<Parts>(0);

	public Shelfs() {
	}

	public Shelfs(String shelf) {
		this.shelf = shelf;
	}

	public Shelfs(String shelf, Set<Parts> parts) {
		this.shelf = shelf;
		this.parts = parts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "shelf_id", unique = true, nullable = false)
	public Integer getShelfId() {
		return this.shelfId;
	}

	public void setShelfId(Integer shelfId) {
		this.shelfId = shelfId;
	}

	@Column(name = "shelf", unique = true, nullable = false)
	public String getShelf() {
		return this.shelf;
	}

	public void setShelf(String shelf) {
		this.shelf = shelf;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shelfs")
	public Set<Parts> getParts() {
		return this.parts;
	}

	public void setParts(Set<Parts> parts) {
		this.parts = parts;
	}

}
